name: Test InfluxDB v2.x

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          - elixir: '1.10.4'
            otp: '21.3'
            influxdb_image_version: '2.0.9'
            influxdb_test_version: '2.0'
          - elixir: '1.12.3'
            otp: '22.3'
            influxdb_image_version: '2.1.1'
            influxdb_test_version: '2.1'
          - elixir: '1.13.4'
            otp: '23.3'
            influxdb_image_version: '2.2.0'
            influxdb_test_version: '2.2'
          - elixir: '1.13.4'
            otp: '24.3'
            influxdb_image_version: '2.3.0'
            influxdb_test_version: '2.3'
          - elixir: '1.14.1'
            otp: '25.0'
            influxdb_image_version: '2.4.0'
            influxdb_test_version: '2.4'

    services:
      influxdb:
        image: influxdb:${{ matrix.influxdb_image_version }}
        ports:
          - 8086:8086

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INFLUXDB_VERSION: ${{ matrix.influxdb_test_version }}

    steps:
    - uses: actions/checkout@v3

    - name: setup
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: mix-cache
      uses: actions/cache@v3
      id: mix-cache
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

    - name: mix-deps
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: test
      run: |
        until curl -s -o /dev/null 'http://localhost:8086' 2>/dev/null; do
          sleep 1
        done

        SETUP=$(
            curl -s \
                -XPOST http://localhost:8086/api/v2/setup \
                -H 'accept: application/json' \
                -d '{
                      "username": "instream_test",
                      "password": "instream_test",
                      "org": "instream_test",
                      "bucket": "test_bucket"
                    }'
        )

        export INFLUXDB_V2_BUCKETID=$(jq -r '.bucket.id' <<< "${SETUP}")
        export INFLUXDB_V2_ORGID=$(jq -r '.org.id' <<< "${SETUP}")
        export INFLUXDB_V2_TOKEN=$(jq -r '.auth.token' <<< "${SETUP}")

        curl -s -o /dev/null \
            -XPOST http://localhost:8086/api/v2/dbrps \
            -H "Authorization: Token ${INFLUXDB_V2_TOKEN}" \
            -H 'accept: application/json' \
            -d "{
                  \"bucketID\": \"${INFLUXDB_V2_BUCKETID}\",
                  \"database\": \"mapped_database\",
                  \"default\": true,
                  \"orgID\": \"${INFLUXDB_V2_ORGID}\",
                  \"retention_policy\": \"mapped_retention\"
                }"

        mix coveralls.github
