name: Test InfluxDB v2.0

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        include:
          - elixir: '1.13.1'
            otp: '24.2'
            runs-on: ubuntu-20.04

    runs-on: ${{ matrix.runs-on }}

    services:
      influxdb:
        image: influxdb:2.0.9
        ports:
          - 8086:8086

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INFLUXDB_VERSION: '2.0'

    steps:
    - uses: actions/checkout@v2

    - name: setup
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: mix-cache
      uses: actions/cache@v1
      id: mix-cache
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

    - name: mix-deps
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: test
      run: |
        until curl -s -o /dev/null 'http://localhost:8086' 2>/dev/null; do
          sleep 1
        done

        SETUP=$(curl -s -XPOST http://localhost:8086/api/v2/setup -H 'accept: application/json' -d "{\"username\": \"instream_test\", \"password\": \"instream_test\", \"org\": \"instream_test\", \"bucket\": \"test_database\"}")

        export INFLUXDB_TOKEN=$(jq -r '.auth.token' <<< "${SETUP}")
        export INFLUXDB_BUCKETID=$(jq -r '.bucket.id' <<< "${SETUP}")

        curl -s -o /dev/null -XPOST http://localhost:8086/api/v2/dbrps -H "Authorization: Token ${INFLUX_TOKEN}" -H 'accept: application/json' -d "{\"org\": \"instream_test\", \"bucketID\": \"${INFLUX_BUCKETID}\", \"database\": \"test_database\", \"retention_policy\": \"autogen\", \"default\": true}"

        mix coveralls.github
