name: Test InfluxDB v1.8

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        include:
          - elixir: '1.9.4'
            otp: '20.3'
            runs-on: ubuntu-20.04
          - elixir: '1.10.4'
            otp: '21.3'
            runs-on: ubuntu-20.04
          - elixir: '1.11.4'
            otp: '22.3'
            runs-on: ubuntu-20.04
          - elixir: '1.12.3'
            otp: '23.3'
            runs-on: ubuntu-20.04
          - elixir: '1.12.3'
            otp: '24.2'
            runs-on: ubuntu-20.04

    runs-on: ${{ matrix.runs-on }}

    services:
      influxdb:
        image: influxdb:1.8.10
        env:
          INFLUXDB_HTTP_AUTH_ENABLED: true
          INFLUXDB_HTTP_FLUX_ENABLED: true
          INFLUXDB_HTTP_UNIX_SOCKET_ENABLED: true
          INFLUXDB_HTTP_BIND_SOCKET: /github/workspace/influxdb.sock
          INFLUXDB_ADMIN_USER: instream_test
          INFLUXDB_ADMIN_PASSWORD: instream_test
          INFLUXDB_USER: instream_guest
          INFLUXDB_USER_PASSWORD: instream_guest
          INFLUXDB_UDP_ENABLED: true
          INFLUXDB_UDP_BIND_ADDRESS: ':8089'
          INFLUXDB_UDP_DATABASE: test_database
          INFLUXDB_UDP_BATCH_SIZE: 1000
          INFLUXDB_UDP_BATCH_TIMEOUT: '1s'
          INFLUXDB_UDP_BATCH_PENDING: 5
        ports:
          - 8086:8086
          - 8089:8089/udp
        volumes:
          - ${{ github.workspace }}:/github/workspace

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INFLXUDB_PORT_UDP: 8089
      INFLUXDB_SOCKET: ${{ github.workspace }}/influxdb.sock
      INFLUXDB_VERSION: '1.8'

    steps:
    - uses: actions/checkout@v2

    - name: setup
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: mix-cache
      uses: actions/cache@v1
      id: mix-cache
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

    - name: mix-deps
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: test
      run: mix coveralls.github
